version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: thales-app-store-unifi-controller_server_1
      APP_PORT: 8443

  server:
    image: jacobalberty/unifi:latest
    user: "1000:1000"
    init: true
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - unifi-data:/unifi

volumes:
  unifi-data:
