version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: thales-app-store-unifi-controller_server_1
      APP_PORT: 8443

  server:
    image: linuxserver/unifi-controller:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure

volumes:
